Fix compatibility issues with update 8
ballerina-platform/module-ballerinax-aws.sns pull request #37
Opened 2023-09-11 11:27 UTC by NipunaRanasinghe

# Description
$subject.

Fixes # (issue)

One line release note: 
- One line describing the feature/improvement/fix made by this PR 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK: 

# Checklist:

### Security checks
 - [ ] Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? 
 - [ ] Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets?

2023-09-24 05:27 UTC, RDPerera approved these changes

2023-09-24 08:55 UTC, RDPerera requested changes
Do we need to change [SNS/Module.md](https://github.com/ballerina-platform/module-ballerinax-aws.sns/blob/main/ballerina/Module.md)

From

```ballerina
sns:TopicAttribute attributes = {
        displayName: "Test"
}
```
Changed to

```ballerina
    sns:TopicAttributes attributes = {
        "displayName" : "Test"
    };
```
as well ?

2023-09-25 03:48 UTC, NipunaRanasinghe commented
> Update Module.md sample

@RDPerera yes we need to. Updated with https://github.com/ballerina-platform/module-ballerinax-aws.sns/pull/37/commits/2fe8e20737f8d3f61aaba1878595e9d0507598ac

2023-09-25 03:49 UTC, RDPerera approved these changes

2023-09-25 04:58 UTC, aneeshafedo approved these changes

2023-09-25 05:16 UTC, merged